"""style_preset sort_order

Revision ID: 07b04bb84aa5
Revises: d97eae38c98a
Create Date: 2026-09-20 19:32:22.847912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b04bb84aa5'
down_revision: Union[str, Sequence[str], None] = 'd97eae38c98a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('style_presets', sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('style_presets', 'sort_order')
    # ### end Alembic commands ###
