"""pattern faces

Revision ID: 0d652353ee51
Revises: 07b04bb84aa5
Create Date: 2026-09-21 13:57:09.020721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d652353ee51'
down_revision: Union[str, Sequence[str], None] = '07b04bb84aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patterns', sa.Column('faces', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patterns', 'faces')
    # ### end Alembic commands ###
